/********************************************************************************
** Form generated from reading UI file 'idbeffectdialog.ui'
**
** Created by: Qt User Interface Compiler version 5.7.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_IDBEFFECTDIALOG_H
#define UI_IDBEFFECTDIALOG_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QDialogButtonBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>

QT_BEGIN_NAMESPACE

class Ui_IdbEffectDialog
{
public:
    QDialogButtonBox *buttonBox;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QLineEdit *typeEdit;
    QLineEdit *actTypeEdit;
    QLineEdit *numActEdit;
    QLineEdit *timerEdit;
    QLineEdit *ab1Edit;
    QLineEdit *ab2Edit;
    QLineEdit *ab3Edit;
    QLineEdit *ab4Edit;
    QLineEdit *ab5Edit;
    QLineEdit *ab6Edit;
    QLineEdit *u28Edit;
    QLineEdit *chanceEdit;
    QLineEdit *mul1Edit;
    QLineEdit *mul2Edit;
    QLineEdit *mul3Edit;
    QLineEdit *mul4Edit;
    QLineEdit *mul5Edit;
    QLineEdit *mul6Edit;
    QLineEdit *u48Edit;
    QLabel *label_20;
    QLabel *label_21;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_26;
    QLabel *label_27;
    QLabel *label_28;
    QLabel *label_29;
    QLabel *label_30;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QLabel *label_38;
    QLineEdit *u4CEdit;
    QLineEdit *u50Edit;
    QLineEdit *u54Edit;
    QLineEdit *u58Edit;
    QLineEdit *u5CEdit;
    QLineEdit *heaEdit;
    QLineEdit *kiEdit;
    QLineEdit *kiRecEdit;
    QLineEdit *stmEdit;
    QLineEdit *stmRecEdit;
    QLineEdit *enStaErEdit;
    QLineEdit *f78Edit;
    QLineEdit *groundSpeedEdit;
    QLineEdit *airSpeedEdit;
    QLineEdit *boostSpeedEdit;
    QLineEdit *dashSpeedEdit;
    QLineEdit *atkEdit;
    QLineEdit *basicKiAtkEdit;
    QLabel *label_39;
    QLabel *label_40;
    QLabel *label_41;
    QLabel *label_42;
    QLabel *label_43;
    QLabel *label_44;
    QLabel *label_45;
    QLabel *label_46;
    QLabel *label_47;
    QLabel *label_48;
    QLabel *label_49;
    QLabel *label_50;
    QLabel *label_51;
    QLabel *label_52;
    QLabel *label_53;
    QLabel *label_54;
    QLabel *label_55;
    QLabel *label_56;
    QLineEdit *strEdit;
    QLineEdit *blaEdit;
    QLineEdit *atkDmgEdit;
    QLineEdit *kiDmgEdit;
    QLineEdit *strDmgEdit;
    QLineEdit *blaDmgEdit;
    QLineEdit *fACEdit;
    QLineEdit *fB0Edit;
    QLineEdit *fB8Edit;
    QLineEdit *fBCEdit;
    QLineEdit *fC0Edit;
    QLineEdit *fC4Edit;
    QLineEdit *fC8Edit;
    QLineEdit *fCCEdit;
    QLineEdit *fD0Edit;
    QLineEdit *fD4Edit;
    QLineEdit *fD8Edit;
    QLineEdit *fDCEdit;
    QLabel *label_25;
    QLineEdit *fB4Edit;
    QLineEdit *nu48Edit;
    QLabel *label_57;
    QLineEdit *nu4CEdit;
    QLabel *label_58;
    QLineEdit *nu0CEdit;
    QLabel *label_59;

    void setupUi(QDialog *IdbEffectDialog)
    {
        if (IdbEffectDialog->objectName().isEmpty())
            IdbEffectDialog->setObjectName(QStringLiteral("IdbEffectDialog"));
        IdbEffectDialog->resize(751, 680);
        buttonBox = new QDialogButtonBox(IdbEffectDialog);
        buttonBox->setObjectName(QStringLiteral("buttonBox"));
        buttonBox->setGeometry(QRect(5, 635, 745, 23));
        buttonBox->setStandardButtons(QDialogButtonBox::Cancel|QDialogButtonBox::Ok);
        buttonBox->setCenterButtons(true);
        label = new QLabel(IdbEffectDialog);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(93, 20, 47, 13));
        label_2 = new QLabel(IdbEffectDialog);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(44, 50, 91, 16));
        label_3 = new QLabel(IdbEffectDialog);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(5, 80, 131, 16));
        label_4 = new QLabel(IdbEffectDialog);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(91, 110, 47, 13));
        label_5 = new QLabel(IdbEffectDialog);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(50, 140, 81, 16));
        label_6 = new QLabel(IdbEffectDialog);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(50, 170, 81, 16));
        label_7 = new QLabel(IdbEffectDialog);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(50, 200, 81, 16));
        label_8 = new QLabel(IdbEffectDialog);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(50, 230, 81, 16));
        label_9 = new QLabel(IdbEffectDialog);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(50, 260, 81, 16));
        label_10 = new QLabel(IdbEffectDialog);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(50, 290, 81, 16));
        label_11 = new QLabel(IdbEffectDialog);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(91, 320, 41, 16));
        label_12 = new QLabel(IdbEffectDialog);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(31, 350, 101, 16));
        label_13 = new QLabel(IdbEffectDialog);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(65, 380, 61, 16));
        label_14 = new QLabel(IdbEffectDialog);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(65, 410, 61, 16));
        label_15 = new QLabel(IdbEffectDialog);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(65, 440, 61, 16));
        label_16 = new QLabel(IdbEffectDialog);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(65, 470, 61, 16));
        label_17 = new QLabel(IdbEffectDialog);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(65, 500, 61, 16));
        label_18 = new QLabel(IdbEffectDialog);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(65, 530, 61, 16));
        label_19 = new QLabel(IdbEffectDialog);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(90, 560, 47, 13));
        typeEdit = new QLineEdit(IdbEffectDialog);
        typeEdit->setObjectName(QStringLiteral("typeEdit"));
        typeEdit->setGeometry(QRect(130, 18, 100, 20));
        actTypeEdit = new QLineEdit(IdbEffectDialog);
        actTypeEdit->setObjectName(QStringLiteral("actTypeEdit"));
        actTypeEdit->setGeometry(QRect(130, 48, 100, 20));
        numActEdit = new QLineEdit(IdbEffectDialog);
        numActEdit->setObjectName(QStringLiteral("numActEdit"));
        numActEdit->setGeometry(QRect(130, 78, 100, 20));
        timerEdit = new QLineEdit(IdbEffectDialog);
        timerEdit->setObjectName(QStringLiteral("timerEdit"));
        timerEdit->setGeometry(QRect(130, 108, 100, 20));
        ab1Edit = new QLineEdit(IdbEffectDialog);
        ab1Edit->setObjectName(QStringLiteral("ab1Edit"));
        ab1Edit->setGeometry(QRect(130, 138, 100, 20));
        ab2Edit = new QLineEdit(IdbEffectDialog);
        ab2Edit->setObjectName(QStringLiteral("ab2Edit"));
        ab2Edit->setGeometry(QRect(130, 168, 100, 20));
        ab3Edit = new QLineEdit(IdbEffectDialog);
        ab3Edit->setObjectName(QStringLiteral("ab3Edit"));
        ab3Edit->setGeometry(QRect(130, 198, 100, 20));
        ab4Edit = new QLineEdit(IdbEffectDialog);
        ab4Edit->setObjectName(QStringLiteral("ab4Edit"));
        ab4Edit->setGeometry(QRect(130, 228, 100, 20));
        ab5Edit = new QLineEdit(IdbEffectDialog);
        ab5Edit->setObjectName(QStringLiteral("ab5Edit"));
        ab5Edit->setGeometry(QRect(130, 258, 100, 20));
        ab6Edit = new QLineEdit(IdbEffectDialog);
        ab6Edit->setObjectName(QStringLiteral("ab6Edit"));
        ab6Edit->setGeometry(QRect(130, 288, 100, 20));
        u28Edit = new QLineEdit(IdbEffectDialog);
        u28Edit->setObjectName(QStringLiteral("u28Edit"));
        u28Edit->setGeometry(QRect(130, 318, 100, 20));
        chanceEdit = new QLineEdit(IdbEffectDialog);
        chanceEdit->setObjectName(QStringLiteral("chanceEdit"));
        chanceEdit->setGeometry(QRect(130, 348, 100, 20));
        mul1Edit = new QLineEdit(IdbEffectDialog);
        mul1Edit->setObjectName(QStringLiteral("mul1Edit"));
        mul1Edit->setGeometry(QRect(130, 378, 100, 20));
        mul2Edit = new QLineEdit(IdbEffectDialog);
        mul2Edit->setObjectName(QStringLiteral("mul2Edit"));
        mul2Edit->setGeometry(QRect(130, 408, 100, 20));
        mul3Edit = new QLineEdit(IdbEffectDialog);
        mul3Edit->setObjectName(QStringLiteral("mul3Edit"));
        mul3Edit->setGeometry(QRect(130, 438, 100, 20));
        mul4Edit = new QLineEdit(IdbEffectDialog);
        mul4Edit->setObjectName(QStringLiteral("mul4Edit"));
        mul4Edit->setGeometry(QRect(130, 468, 100, 20));
        mul5Edit = new QLineEdit(IdbEffectDialog);
        mul5Edit->setObjectName(QStringLiteral("mul5Edit"));
        mul5Edit->setGeometry(QRect(130, 498, 100, 20));
        mul6Edit = new QLineEdit(IdbEffectDialog);
        mul6Edit->setObjectName(QStringLiteral("mul6Edit"));
        mul6Edit->setGeometry(QRect(130, 528, 100, 20));
        u48Edit = new QLineEdit(IdbEffectDialog);
        u48Edit->setObjectName(QStringLiteral("u48Edit"));
        u48Edit->setGeometry(QRect(130, 558, 100, 20));
        label_20 = new QLabel(IdbEffectDialog);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(329, 20, 61, 16));
        label_21 = new QLabel(IdbEffectDialog);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(330, 50, 31, 16));
        label_22 = new QLabel(IdbEffectDialog);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(330, 80, 41, 16));
        label_23 = new QLabel(IdbEffectDialog);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(330, 110, 51, 16));
        label_24 = new QLabel(IdbEffectDialog);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(330, 140, 61, 16));
        label_26 = new QLabel(IdbEffectDialog);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(337, 170, 41, 16));
        label_27 = new QLabel(IdbEffectDialog);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(347, 200, 47, 13));
        label_28 = new QLabel(IdbEffectDialog);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(303, 230, 71, 16));
        label_29 = new QLabel(IdbEffectDialog);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(336, 260, 47, 13));
        label_30 = new QLabel(IdbEffectDialog);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(273, 290, 101, 16));
        label_31 = new QLabel(IdbEffectDialog);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(250, 320, 121, 16));
        label_32 = new QLabel(IdbEffectDialog);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(331, 350, 41, 16));
        label_33 = new QLabel(IdbEffectDialog);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(288, 380, 81, 16));
        label_34 = new QLabel(IdbEffectDialog);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(310, 410, 71, 16));
        label_35 = new QLabel(IdbEffectDialog);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(296, 440, 71, 16));
        label_36 = new QLabel(IdbEffectDialog);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(299, 470, 71, 16));
        label_37 = new QLabel(IdbEffectDialog);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(335, 500, 47, 13));
        label_38 = new QLabel(IdbEffectDialog);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(289, 530, 81, 16));
        u4CEdit = new QLineEdit(IdbEffectDialog);
        u4CEdit->setObjectName(QStringLiteral("u4CEdit"));
        u4CEdit->setGeometry(QRect(370, 18, 100, 20));
        u50Edit = new QLineEdit(IdbEffectDialog);
        u50Edit->setObjectName(QStringLiteral("u50Edit"));
        u50Edit->setGeometry(QRect(370, 48, 100, 20));
        u54Edit = new QLineEdit(IdbEffectDialog);
        u54Edit->setObjectName(QStringLiteral("u54Edit"));
        u54Edit->setGeometry(QRect(370, 78, 100, 20));
        u58Edit = new QLineEdit(IdbEffectDialog);
        u58Edit->setObjectName(QStringLiteral("u58Edit"));
        u58Edit->setGeometry(QRect(370, 108, 100, 20));
        u5CEdit = new QLineEdit(IdbEffectDialog);
        u5CEdit->setObjectName(QStringLiteral("u5CEdit"));
        u5CEdit->setGeometry(QRect(370, 138, 100, 20));
        heaEdit = new QLineEdit(IdbEffectDialog);
        heaEdit->setObjectName(QStringLiteral("heaEdit"));
        heaEdit->setGeometry(QRect(370, 168, 100, 20));
        kiEdit = new QLineEdit(IdbEffectDialog);
        kiEdit->setObjectName(QStringLiteral("kiEdit"));
        kiEdit->setGeometry(QRect(370, 198, 100, 20));
        kiRecEdit = new QLineEdit(IdbEffectDialog);
        kiRecEdit->setObjectName(QStringLiteral("kiRecEdit"));
        kiRecEdit->setGeometry(QRect(370, 228, 100, 20));
        stmEdit = new QLineEdit(IdbEffectDialog);
        stmEdit->setObjectName(QStringLiteral("stmEdit"));
        stmEdit->setGeometry(QRect(370, 258, 100, 20));
        stmRecEdit = new QLineEdit(IdbEffectDialog);
        stmRecEdit->setObjectName(QStringLiteral("stmRecEdit"));
        stmRecEdit->setGeometry(QRect(370, 288, 100, 20));
        enStaErEdit = new QLineEdit(IdbEffectDialog);
        enStaErEdit->setObjectName(QStringLiteral("enStaErEdit"));
        enStaErEdit->setGeometry(QRect(370, 318, 100, 20));
        f78Edit = new QLineEdit(IdbEffectDialog);
        f78Edit->setObjectName(QStringLiteral("f78Edit"));
        f78Edit->setGeometry(QRect(370, 348, 100, 20));
        groundSpeedEdit = new QLineEdit(IdbEffectDialog);
        groundSpeedEdit->setObjectName(QStringLiteral("groundSpeedEdit"));
        groundSpeedEdit->setGeometry(QRect(370, 378, 100, 20));
        airSpeedEdit = new QLineEdit(IdbEffectDialog);
        airSpeedEdit->setObjectName(QStringLiteral("airSpeedEdit"));
        airSpeedEdit->setGeometry(QRect(370, 408, 100, 20));
        boostSpeedEdit = new QLineEdit(IdbEffectDialog);
        boostSpeedEdit->setObjectName(QStringLiteral("boostSpeedEdit"));
        boostSpeedEdit->setGeometry(QRect(370, 438, 100, 20));
        dashSpeedEdit = new QLineEdit(IdbEffectDialog);
        dashSpeedEdit->setObjectName(QStringLiteral("dashSpeedEdit"));
        dashSpeedEdit->setGeometry(QRect(370, 468, 100, 20));
        atkEdit = new QLineEdit(IdbEffectDialog);
        atkEdit->setObjectName(QStringLiteral("atkEdit"));
        atkEdit->setGeometry(QRect(370, 498, 100, 20));
        basicKiAtkEdit = new QLineEdit(IdbEffectDialog);
        basicKiAtkEdit->setObjectName(QStringLiteral("basicKiAtkEdit"));
        basicKiAtkEdit->setGeometry(QRect(370, 528, 100, 20));
        label_39 = new QLabel(IdbEffectDialog);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(577, 20, 47, 13));
        label_40 = new QLabel(IdbEffectDialog);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(577, 50, 47, 13));
        label_41 = new QLabel(IdbEffectDialog);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(489, 80, 121, 16));
        label_42 = new QLabel(IdbEffectDialog);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(522, 110, 101, 16));
        label_43 = new QLabel(IdbEffectDialog);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(500, 140, 101, 16));
        label_44 = new QLabel(IdbEffectDialog);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(490, 170, 121, 16));
        label_45 = new QLabel(IdbEffectDialog);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(570, 200, 51, 16));
        label_46 = new QLabel(IdbEffectDialog);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(571, 230, 51, 16));
        label_47 = new QLabel(IdbEffectDialog);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(571, 290, 61, 16));
        label_48 = new QLabel(IdbEffectDialog);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(570, 320, 41, 16));
        label_49 = new QLabel(IdbEffectDialog);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(571, 350, 41, 16));
        label_50 = new QLabel(IdbEffectDialog);
        label_50->setObjectName(QStringLiteral("label_50"));
        label_50->setGeometry(QRect(571, 380, 41, 16));
        label_51 = new QLabel(IdbEffectDialog);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(571, 410, 47, 13));
        label_52 = new QLabel(IdbEffectDialog);
        label_52->setObjectName(QStringLiteral("label_52"));
        label_52->setGeometry(QRect(571, 470, 47, 13));
        label_53 = new QLabel(IdbEffectDialog);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(571, 500, 47, 13));
        label_54 = new QLabel(IdbEffectDialog);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(571, 530, 47, 13));
        label_55 = new QLabel(IdbEffectDialog);
        label_55->setObjectName(QStringLiteral("label_55"));
        label_55->setGeometry(QRect(570, 560, 47, 13));
        label_56 = new QLabel(IdbEffectDialog);
        label_56->setObjectName(QStringLiteral("label_56"));
        label_56->setGeometry(QRect(570, 440, 47, 13));
        strEdit = new QLineEdit(IdbEffectDialog);
        strEdit->setObjectName(QStringLiteral("strEdit"));
        strEdit->setGeometry(QRect(610, 18, 100, 20));
        blaEdit = new QLineEdit(IdbEffectDialog);
        blaEdit->setObjectName(QStringLiteral("blaEdit"));
        blaEdit->setGeometry(QRect(610, 48, 100, 20));
        atkDmgEdit = new QLineEdit(IdbEffectDialog);
        atkDmgEdit->setObjectName(QStringLiteral("atkDmgEdit"));
        atkDmgEdit->setGeometry(QRect(610, 78, 100, 20));
        kiDmgEdit = new QLineEdit(IdbEffectDialog);
        kiDmgEdit->setObjectName(QStringLiteral("kiDmgEdit"));
        kiDmgEdit->setGeometry(QRect(610, 108, 100, 20));
        strDmgEdit = new QLineEdit(IdbEffectDialog);
        strDmgEdit->setObjectName(QStringLiteral("strDmgEdit"));
        strDmgEdit->setGeometry(QRect(610, 138, 100, 20));
        blaDmgEdit = new QLineEdit(IdbEffectDialog);
        blaDmgEdit->setObjectName(QStringLiteral("blaDmgEdit"));
        blaDmgEdit->setGeometry(QRect(610, 168, 100, 20));
        fACEdit = new QLineEdit(IdbEffectDialog);
        fACEdit->setObjectName(QStringLiteral("fACEdit"));
        fACEdit->setGeometry(QRect(610, 198, 100, 20));
        fB0Edit = new QLineEdit(IdbEffectDialog);
        fB0Edit->setObjectName(QStringLiteral("fB0Edit"));
        fB0Edit->setGeometry(QRect(610, 228, 100, 20));
        fB8Edit = new QLineEdit(IdbEffectDialog);
        fB8Edit->setObjectName(QStringLiteral("fB8Edit"));
        fB8Edit->setGeometry(QRect(610, 288, 100, 20));
        fBCEdit = new QLineEdit(IdbEffectDialog);
        fBCEdit->setObjectName(QStringLiteral("fBCEdit"));
        fBCEdit->setGeometry(QRect(610, 318, 100, 20));
        fC0Edit = new QLineEdit(IdbEffectDialog);
        fC0Edit->setObjectName(QStringLiteral("fC0Edit"));
        fC0Edit->setGeometry(QRect(610, 348, 100, 20));
        fC4Edit = new QLineEdit(IdbEffectDialog);
        fC4Edit->setObjectName(QStringLiteral("fC4Edit"));
        fC4Edit->setGeometry(QRect(610, 378, 100, 20));
        fC8Edit = new QLineEdit(IdbEffectDialog);
        fC8Edit->setObjectName(QStringLiteral("fC8Edit"));
        fC8Edit->setGeometry(QRect(610, 408, 100, 20));
        fCCEdit = new QLineEdit(IdbEffectDialog);
        fCCEdit->setObjectName(QStringLiteral("fCCEdit"));
        fCCEdit->setGeometry(QRect(610, 438, 100, 20));
        fD0Edit = new QLineEdit(IdbEffectDialog);
        fD0Edit->setObjectName(QStringLiteral("fD0Edit"));
        fD0Edit->setGeometry(QRect(610, 468, 100, 20));
        fD4Edit = new QLineEdit(IdbEffectDialog);
        fD4Edit->setObjectName(QStringLiteral("fD4Edit"));
        fD4Edit->setGeometry(QRect(610, 498, 100, 20));
        fD8Edit = new QLineEdit(IdbEffectDialog);
        fD8Edit->setObjectName(QStringLiteral("fD8Edit"));
        fD8Edit->setGeometry(QRect(610, 528, 100, 20));
        fDCEdit = new QLineEdit(IdbEffectDialog);
        fDCEdit->setObjectName(QStringLiteral("fDCEdit"));
        fDCEdit->setGeometry(QRect(610, 558, 100, 20));
        label_25 = new QLabel(IdbEffectDialog);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(571, 260, 47, 13));
        fB4Edit = new QLineEdit(IdbEffectDialog);
        fB4Edit->setObjectName(QStringLiteral("fB4Edit"));
        fB4Edit->setGeometry(QRect(610, 258, 100, 20));
        nu48Edit = new QLineEdit(IdbEffectDialog);
        nu48Edit->setObjectName(QStringLiteral("nu48Edit"));
        nu48Edit->setGeometry(QRect(370, 558, 100, 20));
        label_57 = new QLabel(IdbEffectDialog);
        label_57->setObjectName(QStringLiteral("label_57"));
        label_57->setGeometry(QRect(323, 560, 47, 13));
        nu4CEdit = new QLineEdit(IdbEffectDialog);
        nu4CEdit->setObjectName(QStringLiteral("nu4CEdit"));
        nu4CEdit->setGeometry(QRect(130, 588, 100, 20));
        label_58 = new QLabel(IdbEffectDialog);
        label_58->setObjectName(QStringLiteral("label_58"));
        label_58->setGeometry(QRect(82, 590, 47, 13));
        nu0CEdit = new QLineEdit(IdbEffectDialog);
        nu0CEdit->setObjectName(QStringLiteral("nu0CEdit"));
        nu0CEdit->setGeometry(QRect(370, 588, 100, 20));
        label_59 = new QLabel(IdbEffectDialog);
        label_59->setObjectName(QStringLiteral("label_59"));
        label_59->setGeometry(QRect(323, 590, 49, 16));

        retranslateUi(IdbEffectDialog);

        QMetaObject::connectSlotsByName(IdbEffectDialog);
    } // setupUi

    void retranslateUi(QDialog *IdbEffectDialog)
    {
        IdbEffectDialog->setWindowTitle(QApplication::translate("IdbEffectDialog", "Edit IDB Effect", 0));
        label->setText(QApplication::translate("IdbEffectDialog", "Type:", 0));
        label_2->setText(QApplication::translate("IdbEffectDialog", "Activation type:", 0));
        label_3->setText(QApplication::translate("IdbEffectDialog", "Num of activation times:", 0));
        label_4->setText(QApplication::translate("IdbEffectDialog", "Timer:", 0));
        label_5->setText(QApplication::translate("IdbEffectDialog", "Ability value 1:", 0));
        label_6->setText(QApplication::translate("IdbEffectDialog", "Ability value 2:", 0));
        label_7->setText(QApplication::translate("IdbEffectDialog", "Ability value 3:", 0));
        label_8->setText(QApplication::translate("IdbEffectDialog", "Ability value 4:", 0));
        label_9->setText(QApplication::translate("IdbEffectDialog", "Ability value 5:", 0));
        label_10->setText(QApplication::translate("IdbEffectDialog", "Ability value 6:", 0));
        label_11->setText(QApplication::translate("IdbEffectDialog", "U_28:", 0));
        label_12->setText(QApplication::translate("IdbEffectDialog", "Activation chance:", 0));
        label_13->setText(QApplication::translate("IdbEffectDialog", "Multiplier 1:", 0));
        label_14->setText(QApplication::translate("IdbEffectDialog", "Multiplier 2:", 0));
        label_15->setText(QApplication::translate("IdbEffectDialog", "Multiplier 3:", 0));
        label_16->setText(QApplication::translate("IdbEffectDialog", "Multiplier 4:", 0));
        label_17->setText(QApplication::translate("IdbEffectDialog", "Multiplier 5:", 0));
        label_18->setText(QApplication::translate("IdbEffectDialog", "Multiplier 6:", 0));
        label_19->setText(QApplication::translate("IdbEffectDialog", "U_48:", 0));
        label_20->setText(QApplication::translate("IdbEffectDialog", "U_4C:", 0));
        label_21->setText(QApplication::translate("IdbEffectDialog", "U_50:", 0));
        label_22->setText(QApplication::translate("IdbEffectDialog", "U_54:", 0));
        label_23->setText(QApplication::translate("IdbEffectDialog", "U_58:", 0));
        label_24->setText(QApplication::translate("IdbEffectDialog", "U_5C:", 0));
        label_26->setText(QApplication::translate("IdbEffectDialog", "HEA:", 0));
        label_27->setText(QApplication::translate("IdbEffectDialog", "KI:", 0));
        label_28->setText(QApplication::translate("IdbEffectDialog", "Ki recovery:", 0));
        label_29->setText(QApplication::translate("IdbEffectDialog", "STM:", 0));
        label_30->setText(QApplication::translate("IdbEffectDialog", "Stamina recovery:", 0));
        label_31->setText(QApplication::translate("IdbEffectDialog", "Enemy stamina eraser:", 0));
        label_32->setText(QApplication::translate("IdbEffectDialog", "F_78:", 0));
        label_33->setText(QApplication::translate("IdbEffectDialog", "Ground speed:", 0));
        label_34->setText(QApplication::translate("IdbEffectDialog", "Air speed:", 0));
        label_35->setText(QApplication::translate("IdbEffectDialog", "Boost speed:", 0));
        label_36->setText(QApplication::translate("IdbEffectDialog", "Dash speed:", 0));
        label_37->setText(QApplication::translate("IdbEffectDialog", "ATK:", 0));
        label_38->setText(QApplication::translate("IdbEffectDialog", "Basic Ki Atack:", 0));
        label_39->setText(QApplication::translate("IdbEffectDialog", "STR:", 0));
        label_40->setText(QApplication::translate("IdbEffectDialog", "BLA:", 0));
        label_41->setText(QApplication::translate("IdbEffectDialog", "Normal attack damage:", 0));
        label_42->setText(QApplication::translate("IdbEffectDialog", "Ki blast damage:", 0));
        label_43->setText(QApplication::translate("IdbEffectDialog", "Super strike damage:", 0));
        label_44->setText(QApplication::translate("IdbEffectDialog", "Super Ki Blast Damage:", 0));
        label_45->setText(QApplication::translate("IdbEffectDialog", "F_AC:", 0));
        label_46->setText(QApplication::translate("IdbEffectDialog", "F_B0:", 0));
        label_47->setText(QApplication::translate("IdbEffectDialog", "F_B8:", 0));
        label_48->setText(QApplication::translate("IdbEffectDialog", "F_BC:", 0));
        label_49->setText(QApplication::translate("IdbEffectDialog", "F_C0:", 0));
        label_50->setText(QApplication::translate("IdbEffectDialog", "F_C4:", 0));
        label_51->setText(QApplication::translate("IdbEffectDialog", "F_C8:", 0));
        label_52->setText(QApplication::translate("IdbEffectDialog", "F_D0:", 0));
        label_53->setText(QApplication::translate("IdbEffectDialog", "F_D4:", 0));
        label_54->setText(QApplication::translate("IdbEffectDialog", "F_D8:", 0));
        label_55->setText(QApplication::translate("IdbEffectDialog", "F_DC:", 0));
        label_56->setText(QApplication::translate("IdbEffectDialog", "F_CC:", 0));
        label_25->setText(QApplication::translate("IdbEffectDialog", "F_B4:", 0));
        label_57->setText(QApplication::translate("IdbEffectDialog", "NU_48:", 0));
        label_58->setText(QApplication::translate("IdbEffectDialog", "NU_4C:", 0));
        label_59->setText(QApplication::translate("IdbEffectDialog", "NU_0C:", 0));
    } // retranslateUi

};

namespace Ui {
    class IdbEffectDialog: public Ui_IdbEffectDialog {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_IDBEFFECTDIALOG_H
